### ISSUE TITLE
Request: Send chat to whichever tab you're viewing

### ISSUE THREAD

**Issue by LonePaladin** [cswendrowski/FoundryVTT-Tabbed-Chatlog#14] opened 2020-08-22 17:37 UTC
It can be easy, with multiple chat tabs, to forget to use the appropriate tag to send to the channel you're looking at. You're having a discussion in OOC, forget to use the tag, and have to take a moment to realize that you accidentally sent it to IC because you forgot the /ooc tag.

To avoid this, we could have an option that makes any messages you send default to going to whichever channel you're looking at. If you're in IC, then it'll behave as normal, and you have to use /ooc to send to OOC. If you're looking at OOC, reverse this: make OOC chat the default, and require you to use the /ic tag to speak in character.

The Rolls channel would need a drop-down or toggle to tell it which of the other tabs to consider the default.

**Comment by cswendrowski** [comment] 2020-09-09 14:15
Duplicate of #7

**Closed by cswendrowski** 2020-09-09 14:15 UTC
